# ColdFront settings overrides, included last so these win.
# Handles: database, secret key, and LDAP authentication (login against the
# same directory the cluster uses). Plugin enablement (Slurm, LDAP search) is
# done via environment variables in docker-compose.yml.
import ldap
from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

DEBUG = True
ALLOWED_HOSTS = ["*"]
SECRET_KEY = "lab-insecure-secret-key-change-me"

# --- Database: our Postgres container ----------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "coldfront",
        "USER": "coldfront",
        "PASSWORD": "coldfront",
        "HOST": "coldfront-db",
        "PORT": "5432",
    }
}

# --- LDAP authentication (login) ---------------------------------------------
# Users log into ColdFront with their directory password. On first login their
# ColdFront account is auto-created. This is the SAME directory SSSD uses on
# the cluster nodes — one identity source.
AUTH_LDAP_SERVER_URI = "ldap://openldap"
AUTH_LDAP_BIND_DN = "cn=admin,dc=cluster,dc=local"
AUTH_LDAP_BIND_PASSWORD = "adminpassword"
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    "ou=people,dc=cluster,dc=local", ldap.SCOPE_SUBTREE, "(uid=%(user)s)"
)
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "cn",
    "last_name": "sn",
    "email": "mail",
}
# Don't require StartTLS in the lab (plain ldap://).
AUTH_LDAP_CONNECTION_OPTIONS = {ldap.OPT_REFERRALS: 0}
AUTH_LDAP_ALWAYS_UPDATE_USER = True

# LDAP first, then local Django accounts (so the local superuser still works).
# NOTE: keep django_su.backends.SuBackend — ColdFront only wires up the "su/"
# URLs (which define su_login) when this backend is present, and the Django
# admin Users page renders a django_su "Login as" button that reverses
# su_login. Drop it and /admin/auth/user/ raises NoReverseMatch.
AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",
    "django_su.backends.SuBackend",
]

# --- Friendly Slurm attribute names ------------------------------------------
# Rename the attributes the Slurm plugin reads to human labels. Admins set a
# "Slurm Account Name"; the "Slurm Group/Per-User Limits" are auto-generated by
# the cf_slurm_limits hook from the simple per-limit fields.
SLURM_ACCOUNT_ATTRIBUTE_NAME = "Slurm Account Name"
SLURM_SPECS_ATTRIBUTE_NAME = "Slurm Group Limits (Generated)"
SLURM_USER_SPECS_ATTRIBUTE_NAME = "Slurm Per-User Limits (Generated)"
SLURM_PARENT_ATTRIBUTE_NAME = "Slurm Parent Account"

# --- Our hook app: compiles friendly limit fields → the slurm_specs above ----
# Guard against double-add (settings can be included more than once).
if "cf_slurm_limits" not in INSTALLED_APPS:
    INSTALLED_APPS = list(INSTALLED_APPS) + ["cf_slurm_limits"]

# --- Trim unused ColdFront modules -------------------------------------------
# Remove Publications, Grants, and Research Output from the nav/project pages
# (they're irrelevant to a pure compute-allocation portal). Also drop the
# project-review nag that asks PIs to enter publications/grants.
GRANT_ENABLE = False
PUBLICATION_ENABLE = False
RESEARCH_OUTPUT_ENABLE = False
PROJECT_ENABLE_PROJECT_REVIEW = False
# NOTE: Field of Science can't be disabled — Project.field_of_science is a
# required field. We keep a single default option instead (see seed).
